---
driver:
  provision: true

provisioner:
  name: puppet_apply
  manifests_path: manifests
  manifest: local.pp
  modules_path: modules
  hiera_data_path: data_testing
  hiera_deep_merge: true
  puppet_verbose: true
  puppet_debug: false
  require_chef_for_busser: false
  require_puppet_repo: false
  custom_options: '--show_diff'
  verify_host_key: false
  hiera_config_path: "hiera-testing.yaml"
  #custom_options: '--show_diff --debug'
  #custom_options: '--show_diff --noop'

transport:
  name: sftp

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: ubuntu-desktop
    driver_plugin: vagrant
    driver_config:
      customize:
        audio: "none"
    driver:
      vagrantfile_erb: vagrantfiles/Vagrantfile-debianoid.erb
      box: bento/ubuntu-22.04
      box_url: https://app.vagrantup.com/bento/boxes/ubuntu-20.04
      customize: 
        memory: 8192
      gui: true
      synced_folders:
        - ['./files', '/tmp/files']
suites:
  - name: default
