#!/bin/bash


if [ "$(whoami)" != "root" ];then
  echo "INFO: not root, executing myself with sudo"
  exec sudo $0
fi
unset LC_ALL
unset LANG
set -x
set -e
apt autoremove -o Acquire::ForceIPv4=true --purge
apt update -o Acquire::ForceIPv4=true
apt upgrade -o Acquire::ForceIPv4=true
apt autoremove -o Acquire::ForceIPv4=true --purge
apt dist-upgrade -o Acquire::ForceIPv4=true
apt autoremove -o Acquire::ForceIPv4=true --purge
which fwupdmgr &>/dev/null && fwupdmgr update
flatpak update --assumeyes
