#!/bin/bash


if [ "$(whoami)" != "root" ];then
  echo "INFO: not root, executing myself with sudo"
  exec sudo $0
fi
unset LC_ALL
unset LANG
set -x
set -e
systemd-inhibit apt autoremove -o Acquire::ForceIPv4=true --purge
systemd-inhibit apt update -o Acquire::ForceIPv4=true
systemd-inhibit apt upgrade -o Acquire::ForceIPv4=true
systemd-inhibit apt autoremove -o Acquire::ForceIPv4=true --purge
systemd-inhibit apt dist-upgrade -o Acquire::ForceIPv4=true
systemd-inhibit apt autoremove -o Acquire::ForceIPv4=true --purge
which fwupdmgr &>/dev/null && systemd-inhibit fwupdmgr update
systemd-inhibit flatpak update --assumeyes
